unique_ids:
  forms:
    HomePage: ZRJI74JUAF6AEINWJO6YM2EES2CZS4YL
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: HL4NC4GQ2R26NOFHI2OB4EN5UGXXQSUW
    theme.css: NPRYGWCZOTIHJZDCTRHAQ6N4PUABEJ6C
  scripts: {}
